### ISSUE TITLE
Incompatible with Fastload

### ISSUE THREAD

**Issue by BLUEChester** [mineblock11/Seamless-Loading-Screen-Renewed#2]
It crashes with Fastload
It actually works with Bedrockify but it sort of switches back and forth from Bedrockify's loading screen to this mods screen.
It can be fixed by simply turning Bedrockify's loading screen off in the config

I don't actually want these fixed, I'll be using this mod over Bedrockify's loading screen, and would rather use this mod over Fastload. I just wanted to let you know.

You're welcome to close this straight away.

**Comment by mineblock11** [comment]
I'll take a look at Bedrockify support, and could you provide the logs for fastload?

**Comment by mineblock11** [comment]
Compatability for bedrockify has been added, will release soon.
